import { OnInit } from '@angular/core';
export declare class SukuCardLineComponent implements OnInit {
    image: string;
    chatReadIcon: string;
    chatUnreadIcon: string;
    msgStatus: string;
    customclass: string;
    customIconclass: string;
    bgColor: string;
    interest: any;
    imageColSize: string;
    txtcolsize: string;
    txttwocolsize: string;
    txtthreecolsize: string;
    titleOne: string;
    titleOneColor: string;
    titleOneWeight: string;
    titleOneSize: string;
    titleOnecustomclass: string;
    contentOne: string;
    contentOneColor: string;
    contentOneWeight: string;
    contentOneSize: string;
    contentOnecustomclass: string;
    contentTwo: string;
    contentTwoColor: string;
    contentTwoWeight: string;
    contentTwoSize: string;
    contentTwocustomclass: string;
    subTitleTwo: string;
    subTitleTwoColor: string;
    subTitleTwoWeight: string;
    subTitleTwoSize: string;
    subTitleTwocustomclass: string;
    subTitleThree: string;
    subTitleThreecolor: string;
    subTitleThreeWeight: string;
    subTitleThreeSize: string;
    subTitleThreeClass: string;
    contentThree: string;
    contentThreeColor: string;
    contentThreeWeight: string;
    contentThreeSize: string;
    contentThreecustomclass: string;
    constructor();
    ngOnInit(): void;
}
