import { OnInit, EventEmitter } from '@angular/core';
export declare class SukuFormTableComponent implements OnInit {
    j: any;
    _items: any[];
    _itemsKey: any;
    editable: any[];
    errorvalidationIndex: any;
    errorvalidationKey: any;
    disableArrList: number[];
    titleOneId: any;
    titleOneSize: any;
    titleOneColor: string;
    titleOneWeight: any;
    titleOneCustomClass: string;
    titleContent: string;
    headerSize: string;
    headerColor: any;
    headerWeight: any;
    colorPallete: string[];
    status: string[];
    tableDisabled: any[];
    disableHighlightKey: boolean;
    keyLength: number;
    enableEditIndex: any;
    typeKey: any;
    type: any;
    defaultCount: number;
    actionkey: string;
    disabledArrayKey: any[];
    items: any;
    uniqueKey: string;
    selectionKey: any;
    highlighterKey: any;
    patchKey: any;
    hiddenKey: any[];
    enableHighlighter: boolean;
    enableControls: boolean;
    enableSelectAll: boolean;
    selectAll: any;
    keyData: any[];
    controlsSize: any;
    controlCustomClass: any;
    disableSelectAll: boolean;
    patchEmpty: string;
    hideErrorMsg: boolean;
    errorMessageOne: string;
    save: EventEmitter<{}>;
    remove: EventEmitter<{}>;
    submitData: EventEmitter<{}>;
    formStatus: EventEmitter<{}>;
    limit: EventEmitter<{}>;
    sortable: string;
    maxRowLength: number;
    _null: any;
    blockPaste(e: KeyboardEvent): void;
    blockCopy(e: KeyboardEvent): void;
    blockCut(e: KeyboardEvent): void;
    constructor();
    ngOnInit(): void;
    addTable(val: any, editIndex: any): void;
    submit(): void;
    edit(i: any, item: any): void;
    removedata(i: any, item: any): void;
    checkValid(list: any): boolean;
    selectAllAction(): void;
    chkHiddenKey(key: any): boolean;
    patchValue(selection: any, defaultValue: any, index: any, key?: any): Promise<void>;
    sendData(): void;
    validate(key: any, index: any): void;
    checkSpcialChar(event: any, type: any): boolean;
    sort(head: any, type: any, sortOption: any): void;
}
