import { OnInit, EventEmitter } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { MatSnackBar } from '@angular/material';
export declare class SukuBeneficialOwnerComponent implements OnInit {
    private snackBar;
    form: FormGroup;
    title: string;
    titleClass: string;
    titleCustomClass: string;
    titleid: string;
    titleWeight: string;
    titleColor: string;
    titleSize: string;
    countriesList: any;
    statesList: any;
    formValid: Boolean;
    control: string;
    arrayControlName: any;
    content: string;
    countrySelect: EventEmitter<{}>;
    stateSelect: EventEmitter<{}>;
    upload: EventEmitter<{}>;
    submitOwner: EventEmitter<{}>;
    add: EventEmitter<{}>;
    submitData: EventEmitter<{}>;
    verify: EventEmitter<{}>;
    selected: any[];
    toggle: any[];
    customClass: any;
    documentType: any;
    uploadType: any;
    type: string;
    btnOne: string;
    btnOneId: string;
    btnOneCustomClass: string;
    btnOneDisable: Boolean;
    btnTwo: string;
    btnTwoCustomClass: string;
    btnTwoId: string;
    btnTwoDisable: Boolean;
    labelOne: string;
    labelOneId: string;
    constructor(snackBar: MatSnackBar);
    ngOnInit(): void;
    active(i: any): void;
    action(): void;
    countrySelectAction(val: any, i: any): void;
    agree(): void;
    submitDatas(): void;
    snackbar(msg: any): void;
}
