import { OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { MatDialogRef, MatSnackBar } from '@angular/material';
export declare class SukuAddLicenseModalComponent implements OnInit {
    private snackBar;
    dialogCustomRef: MatDialogRef<SukuAddLicenseModalComponent>;
    data: any;
    formSumitAttempt: boolean;
    _subscriptionOne: any;
    _subscriptionTwo: any;
    _subscriptionThree: any;
    _subscriptionFour: any;
    _subscribeFiles: any;
    controlOneValue: any;
    controlTwoValue: any;
    dateControlOneValue: any;
    dateControlTwoValue: any;
    mulFiles: any[];
    uploadFiles: any[];
    dialogData: {
        controlOne: string;
        controlTwo: string;
        dateControlOne: string;
        dateControlTwo: string;
        'controlOnePatternEnabled': string;
        'controlTwoPatternEnabled': string;
        controlOneRequired: string;
        controlTwoRequired: string;
        controlTwoRequiredd: string;
        dateControlOneRequired: string;
        dateControlTwoRequired: string;
        'controlOnePattern': string;
        'controlTwoPattern': string;
        'title': string;
        'subTitle': string;
        'controlHint': string;
        'hintClass': string;
        'headerCutomStyle': string;
        'startDateMaxDate': string;
        'endDateMaxDate': string;
        'startDateMinDate': string;
        'endDateMinDate': string;
        'controlOneId': string;
        controlTwoId: string;
        dateControlOneId: string;
        dateControlTwoId: string;
        controlTwoToolTip: string;
        controlOnePlaceholder: string;
        controlTwoPlaceholder: string;
        dateControlOnePlaceholder: string;
        dateControlTwoPlaceholder: string;
        controlOneRquiredErrorMsg: string;
        controlTwoRquiredErrorMsg: string;
        controlTwoPatternErrorMsg: string;
        dateControlOneRquiredErrorMsg: string;
        dateControlTwoRquiredErrorMsg: string;
        acceptDocment: string;
        uploadImg: string;
        uploadTitle: string;
        fileListTitle: string;
        fileInputId: string;
        filesArray: any[];
        fileRemoveBtnTxt: string;
        fileRemoveBtnId: string;
        uploadImgAltTxt: string;
        cancelBtnText: string;
        submitBtnTxt: string;
        submitBtnCustomClass: string;
        cancelBtnCustomClass: string;
    };
    controlOne: FormControl;
    controlTwo: FormControl;
    dateControlOne: FormControl;
    dateControlTwo: FormControl;
    constructor(snackBar: MatSnackBar, dialogCustomRef: MatDialogRef<SukuAddLicenseModalComponent>, data: any);
    ngOnInit(): void;
    addLicense(): void;
    closeDialog(): void;
    startUpload(e: any): void;
    removeFile(param: any): void;
    snackbar(msg: any): void;
}
