import { OnInit } from '@angular/core';
export declare class SukuBidTagComponent implements OnInit {
    prize: string;
    prizeSize: string;
    prizeWeight: string;
    prizeColor: string;
    prizeCustomClass: string;
    prizeId: string;
    unit: string;
    unitSize: string;
    unitWeight: string;
    unitColor: string;
    unitCustomClass: string;
    unitId: string;
    qContent: string;
    qSize: string;
    qWeight: string;
    qColor: string;
    qCustomClass: string;
    quantityId: string;
    pContent: string;
    pSize: string;
    pWeight: string;
    pColor: string;
    pCustomClass: string;
    totalPrizeId: string;
    bidtagclass: string;
    constructor();
    ngOnInit(): void;
}
