import { OnInit, EventEmitter } from '@angular/core';
export declare class SukuFormFooterComponent implements OnInit {
    btnOneLabel: string;
    btnOneId: string;
    btnOneSize: string;
    btnOneColor: string;
    btnOneWeight: string;
    btnOneCustomClass: string;
    btnOneVisible: string;
    btnOneAction: EventEmitter<{}>;
    btnTwoLabel: string;
    btnTwoId: string;
    btnTwoSize: string;
    btnTwoColor: string;
    btnTwoWeight: string;
    btnTwoVisible: string;
    btnTwoCustomClass: string;
    btnTwoAction: EventEmitter<{}>;
    btnThreeLabel: string;
    btnThreeId: string;
    btnThreeSize: string;
    btnThreeColor: string;
    btnThreeWeight: string;
    btnThreeVisible: string;
    btnThreeCustomClass: string;
    btnThreeDisableValue: Boolean;
    btnThreeAction: EventEmitter<{}>;
    btnFourLabel: string;
    btnFourId: string;
    btnFourSize: string;
    btnFourColor: string;
    btnFourWeight: string;
    btnFourVisible: string;
    btnFourCustomClass: string;
    btnFourDisableValue: Boolean;
    btnFourAction: EventEmitter<{}>;
    btnThreeType: string;
    btnFourType: string;
    constructor();
    ngOnInit(): void;
}
