import { OnInit, EventEmitter } from '@angular/core';
export declare class SukuMatchChipComponent implements OnInit {
    image: string;
    match: EventEmitter<{}>;
    customclass: string;
    listNameSize: string;
    listWeight: string;
    listColor: string;
    listName: string;
    listCustomClass: string;
    prize: string;
    prizeSize: string;
    prizeWeight: string;
    prizeColor: string;
    prizeCustomClass: string;
    date: string;
    dateSize: string;
    dateWeight: string;
    dateColor: string;
    dateCustomClass: string;
    dateV: string;
    dateVSize: string;
    dateVWeight: string;
    dateVColor: string;
    dateVCustomClass: string;
    sell: string;
    sellSize: string;
    sellWeight: string;
    sellColor: string;
    sellCustomClass: string;
    sellV: string;
    sellVSize: string;
    sellVWeight: string;
    sellVColor: string;
    sellVCustomClass: string;
    id: string;
    constructor();
    ngOnInit(): void;
}
