import { OnInit, EventEmitter } from '@angular/core';
export declare class SukuHeaderComponent implements OnInit {
    _date: any;
    _enableTimer: any;
    titleOne: string;
    titleOneId: any;
    titleOneSize: any;
    titleOneColor: any;
    titleOneWeight: any;
    titleOneCustomClass: any;
    contentOne: string;
    contentOneId: any;
    contentOneSize: any;
    contentOneColor: any;
    contentOneWeight: any;
    contentOneCustomClass: any;
    titleTwo: string;
    titleTwoId: any;
    titleTwoSize: any;
    titleTwoColor: any;
    titleTwoWeight: any;
    titleTwoCustomClass: any;
    contentTwo: string;
    contentTwoId: any;
    contentTwoSize: any;
    contentTwoColor: any;
    contentTwoWeight: any;
    contentTwoCustomClass: string;
    titleThree: string;
    titleThreeId: any;
    titleThreeSize: any;
    titleThreeColor: any;
    titleThreeWeight: any;
    titleThreeCustomClass: any;
    contentThree: any;
    enableTimer: any;
    contentThreeId: any;
    contentThreeSize: any;
    contentThreeColor: any;
    contentThreeWeight: any;
    contentThreeCustomClass: any;
    action: EventEmitter<{}>;
    constructor();
    ngOnInit(): void;
}
